# Generated by Django 5.2.3 on 2025-07-03 09:05

import traceability.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockmodel',
            name='timestamp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.FloatField(default=traceability.models.get_default_timestamp),
        ),
    ]
