# Generated by Django 5.2.3 on 2025-07-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0002_alter_blockmodel_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockmodel',
            name='hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='blockmodel',
            name='nonce',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blockmodel',
            name='previous_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='blockmodel',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
